### PR TITLE
Ruby marshaling

### PR DESCRIPTION
**Pull request by brendon9x**
Hi,

I'm not sure if this interests you, but we're putting these bitsets in memcached, so it probably useful to others as well.

Cheers,
Brendon.

### CODE REVIEW

**Comment by brendon9x** [comment]
Added a fix for 32 bit systems.

**Comment by tyler** [comment]
Interesting choice, using an array of integers for serialization. Any reason you didn't go with a string?

**Comment by brendon9x** [comment]
Well, I didn't put too much thought into it, but didn't want to bloat the storage size with the existing base 2 string conversion. I also thought it would be the fastest.  Given that marshalling is not really designed for IPC I thought it made sense.  If I was writing to_yaml or to_json methods, I would have had a different set of tradeoffs (and thought about it more).

What is your concern?  I'd also be interested in what format you'd use for a string?

**Comment by tyler** [comment]
Well given that it doesn't need to be printable, I'd probably go with a straight binary representation. I'll give it a try quick.

**Comment by brendon9x** [comment]
Interested to see what you come up with.  

I think the main problem with my implementation is that I'm using unsigned ints instead of signed ints which results in implicit conversion to Bignum if bits 62 or 63 are set.  Which will mess up performance and increase the footprint.

**Comment by tyler** [comment]
Just pushed an attempt. Check it out, if you have time, and let me know if that works for you.

**Comment by brendon9x** [comment]
Hi Tyler,

I just tested both on a 64 bit Mac on 1.9.2 and on 32 bit Linux on 1.8.7 and it works fine.  I was slightly worried about the consistency of string conversions between 1.8 and 1.9, but it doesn't appear to be a problem.

Works for me.  Make sure you take the 32 bit fix as well.

Thanks,
Brendon.

**Comment by brendon9x** [comment]
Contains yet another fix (this time for cardinality, plus merged your marshal changes.

**Comment by tyler** [comment]
All merged in and pushed out 0.1.0.

**Pull request closed without merging**
